config:
  email:
    user_name: "no-reply@reedem.site"
    password: "2NN7baa7i5"
    creative:
      path: "creative"
      file_name: "saludando.html"
    data:
      path: "data"
      file_name: "example-data.xlsx"
    email_data:
      sender: "no-reply@reedem.site"
      subject: "Hola es solo un mensaje de prueba - subject"
      bodytext: "Hola solo es un mensaje de prueba"
    SMTP_SSL:
      port: 465
      host: "mail.reedem.site"